---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-files
data:
  index.html: | # The main page of our application
    <body style="background-color: #000">
     <h1 style="color: #fff; text-align: center">:D</h1>
    </body>
